# -------------------------------------------------------------------
# [ Application Configuration ]
# -------------------------------------------------------------------
server:
  port: 80

# -------------------------------------------------------------------
# [ Spring Configuration ]
# -------------------------------------------------------------------
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/demo?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: wnfjdwnfjd
  jackson:
    serialization:
      indent-output: true

# -------------------------------------------------------------------
# [ MyBatis ]
# -------------------------------------------------------------------
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml


# -------------------------------------------------------------------
# [ logback ]
# -------------------------------------------------------------------
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE