# -------------------------------------------------------------------
# [ Application Configuration ]
# -------------------------------------------------------------------
server:
  port: 80

# -------------------------------------------------------------------
# [ Spring Configuration ]
# -------------------------------------------------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wnfjdwnfjd
    driver-class-name: com.mysql.cj.jdbc.Driver

# -------------------------------------------------------------------
# [ MyBatis ]
# -------------------------------------------------------------------
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: luji.demo.os01.dto